export const NewsContainer: string;
export const Title: string;
export const Description: string;
export const Container: string;
export const Header: string;
export const Date: string;
export const Image: string;
export const Loading: string;
export const ImageContainer: string;