export const Container: string;
export const Header: string;
export const NewsContainer: string;
export const Title: string;
export const Description: string;
export const Link: string;
export const ImageContainer: string;
export const Image: string;
export const Loading: string;
