export const DashboardContainer: string;
export const RowA: string;
export const RowB: string;
export const ColA: string;
export const ColB: string;
export const ColC: string;
export const Tile: string;
export const BlueBackground: string;
export const WhiteBackground: string;
