export const CrisisPreviewImage: string;
export const CrisisPreviewSupportContainer: string;
export const CrisisPreviews: string;
export const CrisisPreviewsButton: string;
export const CrisisPreviewsButtonContainer: string;
export const CrisisPreviewsSupportContainer: string;
export const CrisisPreviewsText: string;
export const CrisisPreviewSupportText: string;
export const CrisisPreviewsOverallContainer: string;
